### ISSUE TITLE
Failed to resolve directive:drag

### ISSUE THREAD

**Issue by haoxl3** [BosenY/vue-drag#1]
我把这个插件放到nuxt框架中，怎么没起作用呢？报题目的错误。在nuxt.config.js中引入的

**Comment by BosenY** [comment]
抱歉啊，好久没维护了，下班回家我赶紧看一下

**Comment by BosenY** [comment]
刚才看了一下，是因为nuxt.config.js默认启用了eslint的原因,目前你只需要将build当中的
`extend(config, {isDev, isClient}) {
      if (isDev && isClient) {
        config
          .module
          .rules
          .push({enforce: 'pre', test: /\.(js|vue)$/, loader: 'eslint-loader', exclude: /(node_modules)/})
      }
    }`
注释掉，就可以使用，不过我在今天晚一点会将插件重新升级一下将eslint等都加入进去，谢谢你的issue！

**Comment by haoxl3** [comment]
后来好用了，但第二个demo没起作用，就是指定地方可以拖动的那个案例。而且我觉得应该加上拖动范围，不能拖出屏幕

**Comment by BosenY** [comment]
好的，这个这两天去加一下

**Comment by BosenY** [comment]
@haoxl3  你说的那种直接用css就可以实现，在外层设置relative 、 overflow设置为hidden即可
