### ISSUE TITLE
package.json 没有entry 入口

### ISSUE THREAD

**Issue by AlwaysSkylll** [BosenY/vue-drag#2]
package.json 没有entry 入口， 导致我import 进来不能引入吧。一直让我npm install

**Comment by BosenY** [comment]
@AlwaysSkylll 我知道了，谢谢提醒，现在加上去

**Comment by AlwaysSkylll** [comment]
已经好辣。移动端不能兼容小遗憾呐

**Comment by BosenY** [comment]
@AlwaysSkylll  当初就只是为了PC所以只写了mouse有关的事件， 给你推荐个库 hammerjs ，这个移动端和PC都支持，我这个我再研究一下怎么写移动端的，哈哈

**Comment by AlwaysSkylll** [comment]
🐒啊
