### ISSUE TITLE
Can I save the drag position?

### ISSUE THREAD

**Issue by wufeng123456** [BosenY/vue-drag#4]

**Comment by BosenY** [comment]
不支持，如果你只是个别几个想保存的话，你可以在dom上绑定一个mouseup事件，然后在里面去做本地存储就可以了。

**Comment by kajweb** [comment]
是否支持排序。就是可以整齐统一的排序

**Comment by BosenY** [comment]
@kajweb 这个插件纯粹是为了实现PC端上类似于[易企秀](https://www.eqxiu.com/)那样去制作页面时拖拽的功能，你说的这个功能我想应该用这个组件： [Vue.Draggable](https://github.com/SortableJS/Vue.Draggable)
