### ISSUE TITLE
有添加缩放元素大小的功能的计划不？

### ISSUE THREAD

**Issue by Kennersky** [BosenY/vue-drag#5]
如题，往往实现了自由拖动后，resize元素大小也就有需要了

**Comment by BosenY** [comment]
这个小插件就是一个实现思路，其实很简单的，因为我自己现在有其他的学习方向，所以这个项目基本不准备维护了，你们可以自己去实现下，或者应该已经有现成的组件可以使用了

**Comment by BosenY** [comment]
你说的这样的功能其实已经算是组件功能了，因为自定义指令基本都是处理某个简单的事件，你可以fork下来自己去进行一下拓展或者直接找找现成的组件（应该有）
